c_stdlib_version:  # [unix]
  - '2.28'  # [linux and not ppc64le]
docker_image:  # [linux and (x86_64 or aarch64)]
  - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux and (x86_64 or aarch64)]
channel_sources:  # [win]
  - conda-forge/label/m2w64-experimental,conda-forge  # [win]
  - conda-forge,defaults  # [ppc64le]
