c_stdlib_version:  # [unix]
  - '2.28'  # [linux and x86_64]
docker_image:
  - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux and x86_64]
channel_sources:  # [win]
  - conda-forge/label/m2w64-experimental,conda-forge  # [win]
channel_targets:  # [win]
  - conda-forge m2w64-experimental  # [win]
