c_stdlib_version:  # [unix]
  - '2.28'  # [linux]
docker_image:
  - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux]
channel_sources:  # [win]
  - conda-forge/label/m2w64-experimental,conda-forge  # [win]
