{% set linux_version = "2.2.11" %}
{% set version = "2.4.4" %}

package:
  name: sbcl
  version: {{ linux_version }}       # [linux64]
  version: {{ version }}             # [(win or osx) and x86_64 or aarch64 or (osx and arm64)]

source:
  - url: http://prdownloads.sourceforge.net/sbcl/sbcl-{{ linux_version }}-x86-64-linux-binary.tar.bz2      # [linux64]
    sha256: 477a885b260c8cf8c794e0c9af0769303706f11e51367dad48e5b402ad0a9493                               # [linux64]

  - url: http://prdownloads.sourceforge.net/sbcl/sbcl-{{ version }}-source.tar.bz2                         # [(win or osx) and x86_64 or aarch64 or (osx and arm64)]
    sha256: 8a932627b3f1d8e9618f1cdc225edcb002456804697e2c87d140683764a106d5                               # [(win or osx) and x86_64 or aarch64 or (osx and arm64)]
    folder: sbcl-source                                                                                    # [(win or osx) and x86_64 or aarch64 or (osx and arm64)]
    patches:
      - patches/0001-osx-update-flags-zstd.patch  # [osx and x86_64]
      - patches/0002-osx-update-rpath-sbcl.patch  # [osx and x86_64]
      - patches/0001-win-use-env-xargs.sh.patch  # [win and x86_64]
      - patches/0002-win-update-flags-zstd.patch  # [win and x86_64]

      - patches/0001-cross-use-qemu.patch  # [aarch64]

      - patches/0001-osx_arm64-update-flags-zstd.patch  # [osx and arm64]
      - patches/0001-aarch64-update-flags-zstd.patch  # [aarch64]
      - patches/0002-aarch64-add-dlopen.patch  # [aarch64]

build:
  skip: true  # [not (osx and arm64)]
  number: 6

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib('c') }}  # [not win]
    # Current windows gcc toolchain (v5.3) segfaults when building SBCL, need >=12
    # Using experimental msys2 toolchain for now
    - mingw-w64-ucrt-x86_64-gcc  # [win and x86_64]
    - mingw-w64-ucrt-x86_64-gcc-libs  # [win and x86_64]
    - mingw-w64-ucrt-x86_64-zstd  # [win and x86_64]
    - make
    - patchelf  # [linux and (build_platform != target_platform)]
    - sbcl  # [build_platform != target_platform]
    - emacs  # [arm64]
  host:
    - zstd  # [(win or osx) and x86_64 or aarch64 or (osx and arm64)]

test:
  commands:
    - test -f ${PREFIX}/etc/conda/activate.d/sbcl-activate.sh  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/etc/conda/deactivate.d/sbcl-deactivate.sh  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - if not exist %PREFIX%\\etc\\conda\\activate.d\\sbcl-activate.bat exit /b 1  # [win]
    - if not exist %PREFIX%\\etc\\conda\\deactivate.d\\sbcl-deactivate.bat exit /b 1  # [win]

    - test -f ${PREFIX}/bin/sbcl  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - if not exist %PREFIX%\\bin\\sbcl.exe exit 1  # [win]

    - test -f ${PREFIX}/lib/sbcl/contrib/asdf.fasl  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/lib/sbcl/contrib/uiop.fasl  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - if not exist %PREFIX%\\lib\\sbcl\\contrib\\asdf.fasl exit 1  # [win]
    - if not exist %PREFIX%\\lib\\sbcl\\contrib\\uiop.fasl exit 1  # [win]

    # Not all contribs are built on Windows - Note this is for when unix builds from source
    # - test -f  ${PREFIX}/lib/sbcl/contrib/sb-perf.asd  # [linux]
    # - test -f  ${PREFIX}/lib/sbcl/contrib/sb-perf.fasl  # [linux]
    {% set contribs = [
      "sb-aclrepl", "sb-bsd-sockets", "sb-capstone", "sb-cltl2", "sb-concurrency", "sb-cover",
      "sb-executable", "sb-gmp", "sb-grovel", "sb-introspect", "sb-md5", "sb-mpfr",
      "sb-posix", "sb-queue", "sb-rotate-byte", "sb-rt", "sb-simd", "sb-simple-streams", "sb-sprof",
    ] %}
    {% for contrib in contribs %}
    - test -f ${PREFIX}/lib/sbcl/contrib/{{ contrib }}.asd  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/lib/sbcl/contrib/{{ contrib }}.fasl  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - if not exist %PREFIX%\\lib\\sbcl\\contrib\\{{ contrib }}.asd exit 1  # [win]
    - if not exist %PREFIX%\\lib\\sbcl\\contrib\\{{ contrib }}.fasl exit 1  # [win]
    {% endfor %}

    - test -f ${PREFIX}/lib/sbcl/sbcl.core  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/lib/sbcl/sbcl.mk  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/share/doc/sbcl/BUGS  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/share/doc/sbcl/COPYING  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/share/doc/sbcl/CREDITS  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/share/doc/sbcl/NEWS  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - test -f ${PREFIX}/share/man/man1/sbcl.1  # [(osx and x86_64) or aarch64 or (osx and arm64)]
    - if not exist %PREFIX%\\lib\\sbcl\\sbcl.core exit 1  # [win]
    - if not exist %PREFIX%\\lib\\sbcl\\sbcl.mk exit 1  # [win]
    - if not exist %PREFIX%\\share\\doc\\sbcl\\BUGS exit 1  # [win]
    - if not exist %PREFIX%\\share\\doc\\sbcl\\COPYING exit 1  # [win]
    - if not exist %PREFIX%\\share\\doc\\sbcl\\CREDITS exit 1  # [win]
    - if not exist %PREFIX%\\share\\doc\\sbcl\\NEWS exit 1  # [win]
    - if not exist %PREFIX%\\share\\man\\man1\\sbcl.1 exit 1  # [win]

    # Additional functionality tests
    - sbcl --version
    - sbcl --help
    - sbcl --noinform --disable-debugger --eval "(print (require :asdf))" --disable-debugger --eval "(quit)"

about:
  home: http://www.sbcl.org
  license: BSD-2-Clause AND MIT
  summary: Steel Bank Common Lisp (SBCL) is a high performance Common Lisp compiler
  description: |
    Steel Bank Common Lisp (SBCL) is a high performance Common Lisp compiler.
    It is open source / free software, with a permissive license. In addition to the
    compiler and runtime system for ANSI Common Lisp, it provides an interactive
    environment including a debugger, a statistical profiler, a code coverage tool,
    and many other extensions.
  doc_url: http://www.sbcl.org/manual/index.html
  license_file:
    - COPYING
    - CREDITS

extra:
  recipe-maintainers:
    - MementoRC
    - wolfv
    - Tobias-Fischer
