conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_ppc64le: default
  linux_aarch64: default
conda_build:
  pkg_format: '2'
test: native_and_emulated
